version: "3.8"

services:
    app:
        container_name: back-end
        build: .
        ports:
            - 8080:3000
        depends_on:
            postgres_db:
              condition: service_healthy
              
    postgres_db:
        container_name: "${TYPEORM_HOST}"
        image: postgres
        restart: unless-stopped
        volumes:
            - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: "${TYPEORM_USERNAME}"
            POSTGRES_PASSWORD: "${TYPEORM_PASSWORD}"
            POSTGRES_DB: "${TYPEORM_DATABASE}"
        expose:
            - 5432
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
