version: "3.8"

services:
    #- ./db/data:/var/lib/postgresql/data
    application:
        container_name: application
        build:
            context: .
        ports:
            - 8080:3000
        depends_on:
            postgres_db:
                condition: service_healthy

    postgres_db:
        container_name: postgres_db
        image: postgres
        restart: unless-stopped
        volumes:
            - ./db/dump.sql:/docker-entrypoint-initdb.d/dump.sql
        environment:
            LC_ALL: C.UTF-8
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: password
            POSTGRES_DB: postgres
        ports:
            - 5432:5432
        expose:
            - 5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
